language: go
go_import_path: github.com/zznop/sploit
git:
  depth: 1
env:
  - GO111MODULE=on
go: [1.14.x, 1.15.x]
os: [linux, osx]
install:
  - ./_travis/deps.sh
script:
  - export GOMAXPROCS=4
  - export GORACE=halt_on_error=1
  - go test -v -run TestNewELF
  - go test -v -run TestELFBSS
  - go test -v -run TestELFRead
  - go test -v -run TestELFGetSignatureVAddrs
  - go test -v -run TestELFGetOpcodeVAddrs
  - go test -v -run TestRead8
  - go test -v -run TestRead16
  - go test -v -run TestRead32
  - go test -v -run TestRead64
  - go test -v -run TestDisasm
  - go test -v -run TestROPDump
  - go test -v -run TestROPInstrSearch
